# Nord Colorscheme for Kitty
# Based on:
# - https://gist.github.com/marcusramberg/64010234c95a93d953e8c79fdaf94192
# - https://github.com/arcticicestudio/nord-hyper

foreground            #D8DEE9
background            #27234b
selection_foreground  #000000
selection_background  #FFFACD
url_color             #0087BD
cursor                #81A1C1

# black
color0   #000000
color8   #808080

# red
color1   #D90429
color9   #ff0000

# green
color2   #3ad900
color10  #33ff00

# yellow
color3   #FAD000
color11  #ffff00

# blue
color4  #6943ff
color12 #0066ff

# magenta
color5   #ff2c70
color13  #cc00ff

# cyan
color6   #80fcff
color14  #00ffff

# white
color7   #c7c7c7
color15  #ffffff
