#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh --colorblocks &
picom --experimental-backends &
polybar example &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
~/.config/dunst/load.sh &
numlockx &
pulseeffects --gapplication-service &

#bspc monitor -d WEB DEV TERM READ CHILL CHAT ETC
bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width        3
bspc config window_gap          10
bspc config focused_border_color "#4C566A"
bspc config normal_border_color  "#2E3440"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
