;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; │░Created░By░Aditya░Shakya░@adi1090x░░░░░░░░░░░░░░░░░░░░░░░░░│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[color]

;; Use pywal.sh in scripts directory to use colors from an image/wallpaper.

;; main colors
background = #ECEFF4
foreground = #ECEFF4
foreground-alt = #2e3440
alpha = #2E3440

;; shades
shade1 = #2E3440
shade2 = #2E3440
shade3 = #2E3440
shade4 = #2E3440
shade5 = #2E3440
shade6 = #2E3440
shade7 = #2E3440
shade8 = #2E3440

black = #4C566A
red = #bf616a
green = #a3be8c
yellow = #ebcb8b
blue = #81a1c1
magenta = #b48ead
cyan = #88c0d0
white = #e5e9f0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
